image: hub.apsl.net/library/gitlab-builder:latest
before_script:
  - docker info
  - export VERSION=${CI_PIPELINE_ID}-${CI_BUILD_REF:0:8}
  - export IMAGE=${DOCKER_REGISTRY}/apsl/onlysmellz:$CI_BUILD_ID-${CI_BUILD_REF:0:8}
stages:
  - build
  - push
  - deploy_prod
build:
  stage: build
  script:
    - docker-compose -f build.yml build
push:
  stage: push
  only:
    - master
  script:
    - echo "Tagging the build with the name -> ${IMAGE}"
    - docker tag onlysmellz:build ${IMAGE}
    - echo "Pushing the build to $DOCKER_REGISTRY , using the user $DOCKER_LOGIN"
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker push ${IMAGE}
prod:
  stage: deploy_prod
  only:
    - master
  when: manual
  script:
    - echo "$IMAGE -> Deploy manual en mamut (de momento)"
