image: hub.apsl.net/library/gitlab-builder-gce:latest
before_script:
  - docker info
  - export VERSION=${CI_PIPELINE_ID}-${CI_BUILD_REF:0:8}
  - export UWSGI_IMAGE=eu.gcr.io/apsl-hosting/sauron-uwsgi:${VERSION}
stages:
  - build
  - push
  - deploy_prod
build:
  stage: build
  script:
    - docker-compose -f build.yml build
push:
  stage: push
  only:
    - master
  script:
    - echo "Tagging the build with the name -> ${UWSGI_IMAGE}"
    - docker tag onlysmellz:build ${UWSGI_IMAGE}
    - echo "Pushing the build to gcloud"
    - gcloud docker push ${UWSGI_IMAGE}
prod:
  stage: deploy_prod
  only:
    - master
  when: manual
  script:
      - deploy.py deploy sauron sauron sauron-uwsgi=${UWSGI_IMAGE} sauron-daphne=${UWSGI_IMAGE} sauron-runworker=${UWSGI_IMAGE}
