version: '2'
services:
  redis:
    image: redis
  postgres:
    image: apsl/postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uonlysmellz
      POSTGRES_DB: onlysmellzdb
      POSTGRES_PASSWORD: pass
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  uwsgi:
    build:
      context: .
      dockerfile: Dockerfile
    image: onlysmellz:latest
    command: uwsgi
    ports:
      - 8000:8000
    links:
      - redis
  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    image: onlysmellz:latest
    command: daphne
    ports:
      - 8001:8000
    links:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: onlysmellz:latest
    command: runworker
    links:
      - redis