# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='ToiletLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_use', models.BooleanField()),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.Toilet')),
            ],
        ),
    ]
