# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toiletlecture',
            old_name='created_at',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='toiletlecture',
            name='in_use',
        ),
        migrations.AddField(
            model_name='toiletlecture',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
