# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0002_auto_20161012_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletlecture',
            name='value',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=10),
        ),
    ]
