# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.AlterField(
            model_name='toiletlecture',
            name='toilet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.Toilet'),
        ),
    ]
